### ISSUE TITLE
Lack of dependency List in Package.json

### ISSUE THREAD

**Issue by MrPardeep** [smhatre59/cloudstorage#1]
in the Frontend Part of your Project there are few missing dependency, do it complete asap. except this project is not working.

**Comment by smhatre59** [comment]
Ok...I will fix the dependency issue when I get time

**Comment by neerajhiretual** [comment]
For the people who come up here looking for solution: 
`{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.8.5"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "material-ui": "^0.20.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-dropzone": "^3.10.0",
    "react-file-tree": "0.0.8",
    "react-router-dom": "^4.0.0",
    "react-tap-event-plugin": "^2.0.1",
    "superagent": "^3.4.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
`
